// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisstoragev1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	versioned "github.com/devsy-org/api/pkg/clientset/versioned"
	internalinterfaces "github.com/devsy-org/api/pkg/informers/externalversions/internalinterfaces"
	storagev1 "github.com/devsy-org/api/pkg/listers/storage/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyWorkspacePresetInformer provides access to a shared informer and lister for
// DevsyWorkspacePresets.
type DevsyWorkspacePresetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() storagev1.DevsyWorkspacePresetLister
}

type devsyWorkspacePresetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDevsyWorkspacePresetInformer constructs a new informer for DevsyWorkspacePreset type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDevsyWorkspacePresetInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDevsyWorkspacePresetInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDevsyWorkspacePresetInformer constructs a new informer for DevsyWorkspacePreset type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDevsyWorkspacePresetInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevsyWorkspacePresets().List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevsyWorkspacePresets().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevsyWorkspacePresets().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevsyWorkspacePresets().Watch(ctx, options)
			},
		}, client),
		&apisstoragev1.DevsyWorkspacePreset{},
		resyncPeriod,
		indexers,
	)
}

func (f *devsyWorkspacePresetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDevsyWorkspacePresetInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *devsyWorkspacePresetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisstoragev1.DevsyWorkspacePreset{}, f.defaultInformer)
}

func (f *devsyWorkspacePresetInformer) Lister() storagev1.DevsyWorkspacePresetLister {
	return storagev1.NewDevsyWorkspacePresetLister(f.Informer().GetIndexer())
}
