// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisstoragev1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	versioned "github.com/devsy-org/api/pkg/clientset/versioned"
	internalinterfaces "github.com/devsy-org/api/pkg/informers/externalversions/internalinterfaces"
	storagev1 "github.com/devsy-org/api/pkg/listers/storage/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyWorkspaceTemplateInformer provides access to a shared informer and lister for
// DevsyWorkspaceTemplates.
type DevsyWorkspaceTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() storagev1.DevsyWorkspaceTemplateLister
}

type devsyWorkspaceTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDevsyWorkspaceTemplateInformer constructs a new informer for DevsyWorkspaceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDevsyWorkspaceTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDevsyWorkspaceTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDevsyWorkspaceTemplateInformer constructs a new informer for DevsyWorkspaceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDevsyWorkspaceTemplateInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevsyWorkspaceTemplates().List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevsyWorkspaceTemplates().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevsyWorkspaceTemplates().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().DevsyWorkspaceTemplates().Watch(ctx, options)
			},
		}, client),
		&apisstoragev1.DevsyWorkspaceTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *devsyWorkspaceTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDevsyWorkspaceTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *devsyWorkspaceTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisstoragev1.DevsyWorkspaceTemplate{}, f.defaultInformer)
}

func (f *devsyWorkspaceTemplateInformer) Lister() storagev1.DevsyWorkspaceTemplateLister {
	return storagev1.NewDevsyWorkspaceTemplateLister(f.Informer().GetIndexer())
}
