// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	storagev1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyEnvironmentTemplateLister helps list DevsyEnvironmentTemplates.
// All objects returned here must be treated as read-only.
type DevsyEnvironmentTemplateLister interface {
	// List lists all DevsyEnvironmentTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1.DevsyEnvironmentTemplate, err error)
	// Get retrieves the DevsyEnvironmentTemplate from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1.DevsyEnvironmentTemplate, error)
	DevsyEnvironmentTemplateListerExpansion
}

// devPodEnvironmentTemplateLister implements the DevsyEnvironmentTemplateLister interface.
type devPodEnvironmentTemplateLister struct {
	listers.ResourceIndexer[*storagev1.DevsyEnvironmentTemplate]
}

// NewDevsyEnvironmentTemplateLister returns a new DevsyEnvironmentTemplateLister.
func NewDevsyEnvironmentTemplateLister(indexer cache.Indexer) DevsyEnvironmentTemplateLister {
	return &devPodEnvironmentTemplateLister{listers.New[*storagev1.DevsyEnvironmentTemplate](indexer, storagev1.Resource("devpodenvironmenttemplate"))}
}
