// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apismanagementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	versioned "github.com/devsy-org/api/pkg/clientset/versioned"
	internalinterfaces "github.com/devsy-org/api/pkg/informers/externalversions/internalinterfaces"
	managementv1 "github.com/devsy-org/api/pkg/listers/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyWorkspaceInstanceInformer provides access to a shared informer and lister for
// DevsyWorkspaceInstances.
type DevsyWorkspaceInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() managementv1.DevsyWorkspaceInstanceLister
}

type devsyWorkspaceInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDevsyWorkspaceInstanceInformer constructs a new informer for DevsyWorkspaceInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDevsyWorkspaceInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDevsyWorkspaceInstanceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDevsyWorkspaceInstanceInformer constructs a new informer for DevsyWorkspaceInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDevsyWorkspaceInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevsyWorkspaceInstances(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevsyWorkspaceInstances(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevsyWorkspaceInstances(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ManagementV1().DevsyWorkspaceInstances(namespace).Watch(ctx, options)
			},
		}, client),
		&apismanagementv1.DevsyWorkspaceInstance{},
		resyncPeriod,
		indexers,
	)
}

func (f *devsyWorkspaceInstanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDevsyWorkspaceInstanceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *devsyWorkspaceInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apismanagementv1.DevsyWorkspaceInstance{}, f.defaultInformer)
}

func (f *devsyWorkspaceInstanceInformer) Lister() managementv1.DevsyWorkspaceInstanceLister {
	return managementv1.NewDevsyWorkspaceInstanceLister(f.Informer().GetIndexer())
}
