// Code generated by generator. DO NOT EDIT.

package apis

import (
	"github.com/devsy-org/api/pkg/apis/management"
	_ "github.com/devsy-org/api/pkg/apis/management/install" // Install the management group
	managementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	"github.com/devsy-org/api/pkg/apis/virtualcluster"
	_ "github.com/devsy-org/api/pkg/apis/virtualcluster/install" // Install the virtualcluster group
	virtualclusterv1 "github.com/devsy-org/api/pkg/apis/virtualcluster/v1"
	"github.com/devsy-org/apiserver/pkg/builders"
	"k8s.io/apimachinery/pkg/runtime"
)

var (
	localSchemeBuilder = runtime.SchemeBuilder{
		managementv1.AddToScheme,
		virtualclusterv1.AddToScheme,
	}
	AddToScheme = localSchemeBuilder.AddToScheme
)

// GetAllApiBuilders returns all known APIGroupBuilders
// so they can be registered with the apiserver
func GetAllApiBuilders() []*builders.APIGroupBuilder {
	return []*builders.APIGroupBuilder{
		GetManagementAPIBuilder(),
		GetVirtualclusterAPIBuilder(),
	}
}

func GetManagementAPIBuilder() *builders.APIGroupBuilder {
	return builders.NewApiGroupBuilder(
		"management.devsy.sh",
		"github.com/devsy-org/api/pkg/apis/management").
		WithUnVersionedApi(management.ApiVersion).
		WithVersionedApis(
			managementv1.ApiVersion,
		).
		WithRootScopedKinds(
			"AgentAuditEvent",
			"Announcement",
			"App",
			"Backup",
			"Cluster",
			"ClusterAccess",
			"ClusterRoleTemplate",
			"Config",
			"ConvertVirtualClusterConfig",
			"DatabaseConnector",
			"DevsyEnvironmentTemplate",
			"DevsyWorkspacePreset",
			"DevsyWorkspaceTemplate",
			"DirectClusterEndpointToken",
			"Event",
			"Feature",
			"IngressAuthToken",
			"License",
			"LicenseToken",
			"DevsyUpgrade",
			"NodeProvider",
			"NodeType",
			"OIDCClient",
			"OwnedAccessKey",
			"Project",
			"RedirectToken",
			"RegisterVirtualCluster",
			"ResetAccessKey",
			"Self",
			"SelfSubjectAccessReview",
			"SpaceTemplate",
			"SubjectAccessReview",
			"Task",
			"Team",
			"TranslateDevsyResourceName",
			"UsageDownload",
			"User",
			"VirtualClusterSchema",
			"VirtualClusterTemplate",
		)
}
func GetVirtualclusterAPIBuilder() *builders.APIGroupBuilder {
	return builders.NewApiGroupBuilder(
		"virtualcluster.devsy.sh",
		"github.com/devsy-org/api/pkg/apis/virtualcluster").
		WithUnVersionedApi(virtualcluster.ApiVersion).
		WithVersionedApis(
			virtualclusterv1.ApiVersion,
		).
		WithRootScopedKinds()
}
