// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	managementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	scheme "github.com/devsy-org/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyWorkspaceInstancesGetter has a method to return a DevsyWorkspaceInstanceInterface.
// A group's client should implement this interface.
type DevsyWorkspaceInstancesGetter interface {
	DevsyWorkspaceInstances(namespace string) DevsyWorkspaceInstanceInterface
}

// DevsyWorkspaceInstanceInterface has methods to work with DevsyWorkspaceInstance resources.
type DevsyWorkspaceInstanceInterface interface {
	Create(ctx context.Context, devPodWorkspaceInstance *managementv1.DevsyWorkspaceInstance, opts metav1.CreateOptions) (*managementv1.DevsyWorkspaceInstance, error)
	Update(ctx context.Context, devPodWorkspaceInstance *managementv1.DevsyWorkspaceInstance, opts metav1.UpdateOptions) (*managementv1.DevsyWorkspaceInstance, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*managementv1.DevsyWorkspaceInstance, error)
	List(ctx context.Context, opts metav1.ListOptions) (*managementv1.DevsyWorkspaceInstanceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *managementv1.DevsyWorkspaceInstance, err error)
	Up(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceUp *managementv1.DevsyWorkspaceInstanceUp, opts metav1.CreateOptions) (*managementv1.DevsyWorkspaceInstanceUp, error)
	Stop(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceStop *managementv1.DevsyWorkspaceInstanceStop, opts metav1.CreateOptions) (*managementv1.DevsyWorkspaceInstanceStop, error)
	Troubleshoot(ctx context.Context, devPodWorkspaceInstanceName string, options metav1.GetOptions) (*managementv1.DevsyWorkspaceInstanceTroubleshoot, error)
	Cancel(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceCancel *managementv1.DevsyWorkspaceInstanceCancel, opts metav1.CreateOptions) (*managementv1.DevsyWorkspaceInstanceCancel, error)

	DevsyWorkspaceInstanceExpansion
}

// devPodWorkspaceInstances implements DevsyWorkspaceInstanceInterface
type devPodWorkspaceInstances struct {
	*gentype.ClientWithList[*managementv1.DevsyWorkspaceInstance, *managementv1.DevsyWorkspaceInstanceList]
}

// newDevsyWorkspaceInstances returns a DevsyWorkspaceInstances
func newDevsyWorkspaceInstances(c *ManagementV1Client, namespace string) *devPodWorkspaceInstances {
	return &devPodWorkspaceInstances{
		gentype.NewClientWithList[*managementv1.DevsyWorkspaceInstance, *managementv1.DevsyWorkspaceInstanceList](
			"devpodworkspaceinstances",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *managementv1.DevsyWorkspaceInstance { return &managementv1.DevsyWorkspaceInstance{} },
			func() *managementv1.DevsyWorkspaceInstanceList { return &managementv1.DevsyWorkspaceInstanceList{} },
		),
	}
}

// Up takes the representation of a devPodWorkspaceInstanceUp and creates it.  Returns the server's representation of the devPodWorkspaceInstanceUp, and an error, if there is any.
func (c *devPodWorkspaceInstances) Up(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceUp *managementv1.DevsyWorkspaceInstanceUp, opts metav1.CreateOptions) (result *managementv1.DevsyWorkspaceInstanceUp, err error) {
	result = &managementv1.DevsyWorkspaceInstanceUp{}
	err = c.GetClient().Post().
		Namespace(c.GetNamespace()).
		Resource("devpodworkspaceinstances").
		Name(devPodWorkspaceInstanceName).
		SubResource("up").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(devPodWorkspaceInstanceUp).
		Do(ctx).
		Into(result)
	return
}

// Stop takes the representation of a devPodWorkspaceInstanceStop and creates it.  Returns the server's representation of the devPodWorkspaceInstanceStop, and an error, if there is any.
func (c *devPodWorkspaceInstances) Stop(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceStop *managementv1.DevsyWorkspaceInstanceStop, opts metav1.CreateOptions) (result *managementv1.DevsyWorkspaceInstanceStop, err error) {
	result = &managementv1.DevsyWorkspaceInstanceStop{}
	err = c.GetClient().Post().
		Namespace(c.GetNamespace()).
		Resource("devpodworkspaceinstances").
		Name(devPodWorkspaceInstanceName).
		SubResource("stop").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(devPodWorkspaceInstanceStop).
		Do(ctx).
		Into(result)
	return
}

// Troubleshoot takes name of the devPodWorkspaceInstance, and returns the corresponding managementv1.DevsyWorkspaceInstanceTroubleshoot object, and an error if there is any.
func (c *devPodWorkspaceInstances) Troubleshoot(ctx context.Context, devPodWorkspaceInstanceName string, options metav1.GetOptions) (result *managementv1.DevsyWorkspaceInstanceTroubleshoot, err error) {
	result = &managementv1.DevsyWorkspaceInstanceTroubleshoot{}
	err = c.GetClient().Get().
		Namespace(c.GetNamespace()).
		Resource("devpodworkspaceinstances").
		Name(devPodWorkspaceInstanceName).
		SubResource("troubleshoot").
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// Cancel takes the representation of a devPodWorkspaceInstanceCancel and creates it.  Returns the server's representation of the devPodWorkspaceInstanceCancel, and an error, if there is any.
func (c *devPodWorkspaceInstances) Cancel(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceCancel *managementv1.DevsyWorkspaceInstanceCancel, opts metav1.CreateOptions) (result *managementv1.DevsyWorkspaceInstanceCancel, err error) {
	result = &managementv1.DevsyWorkspaceInstanceCancel{}
	err = c.GetClient().Post().
		Namespace(c.GetNamespace()).
		Resource("devpodworkspaceinstances").
		Name(devPodWorkspaceInstanceName).
		SubResource("cancel").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(devPodWorkspaceInstanceCancel).
		Do(ctx).
		Into(result)
	return
}
