// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	managementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	scheme "github.com/devsy-org/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyWorkspaceTemplatesGetter has a method to return a DevsyWorkspaceTemplateInterface.
// A group's client should implement this interface.
type DevsyWorkspaceTemplatesGetter interface {
	DevsyWorkspaceTemplates() DevsyWorkspaceTemplateInterface
}

// DevsyWorkspaceTemplateInterface has methods to work with DevsyWorkspaceTemplate resources.
type DevsyWorkspaceTemplateInterface interface {
	Create(ctx context.Context, devPodWorkspaceTemplate *managementv1.DevsyWorkspaceTemplate, opts metav1.CreateOptions) (*managementv1.DevsyWorkspaceTemplate, error)
	Update(ctx context.Context, devPodWorkspaceTemplate *managementv1.DevsyWorkspaceTemplate, opts metav1.UpdateOptions) (*managementv1.DevsyWorkspaceTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, devPodWorkspaceTemplate *managementv1.DevsyWorkspaceTemplate, opts metav1.UpdateOptions) (*managementv1.DevsyWorkspaceTemplate, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*managementv1.DevsyWorkspaceTemplate, error)
	List(ctx context.Context, opts metav1.ListOptions) (*managementv1.DevsyWorkspaceTemplateList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *managementv1.DevsyWorkspaceTemplate, err error)
	DevsyWorkspaceTemplateExpansion
}

// devPodWorkspaceTemplates implements DevsyWorkspaceTemplateInterface
type devPodWorkspaceTemplates struct {
	*gentype.ClientWithList[*managementv1.DevsyWorkspaceTemplate, *managementv1.DevsyWorkspaceTemplateList]
}

// newDevsyWorkspaceTemplates returns a DevsyWorkspaceTemplates
func newDevsyWorkspaceTemplates(c *ManagementV1Client) *devPodWorkspaceTemplates {
	return &devPodWorkspaceTemplates{
		gentype.NewClientWithList[*managementv1.DevsyWorkspaceTemplate, *managementv1.DevsyWorkspaceTemplateList](
			"devpodworkspacetemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementv1.DevsyWorkspaceTemplate { return &managementv1.DevsyWorkspaceTemplate{} },
			func() *managementv1.DevsyWorkspaceTemplateList { return &managementv1.DevsyWorkspaceTemplateList{} },
		),
	}
}
