// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	managementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	scheme "github.com/devsy-org/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyWorkspacePresetsGetter has a method to return a DevsyWorkspacePresetInterface.
// A group's client should implement this interface.
type DevsyWorkspacePresetsGetter interface {
	DevsyWorkspacePresets() DevsyWorkspacePresetInterface
}

// DevsyWorkspacePresetInterface has methods to work with DevsyWorkspacePreset resources.
type DevsyWorkspacePresetInterface interface {
	Create(ctx context.Context, devsyWorkspacePreset *managementv1.DevsyWorkspacePreset, opts metav1.CreateOptions) (*managementv1.DevsyWorkspacePreset, error)
	Update(ctx context.Context, devsyWorkspacePreset *managementv1.DevsyWorkspacePreset, opts metav1.UpdateOptions) (*managementv1.DevsyWorkspacePreset, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, devsyWorkspacePreset *managementv1.DevsyWorkspacePreset, opts metav1.UpdateOptions) (*managementv1.DevsyWorkspacePreset, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*managementv1.DevsyWorkspacePreset, error)
	List(ctx context.Context, opts metav1.ListOptions) (*managementv1.DevsyWorkspacePresetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *managementv1.DevsyWorkspacePreset, err error)
	DevsyWorkspacePresetExpansion
}

// devsyWorkspacePresets implements DevsyWorkspacePresetInterface
type devsyWorkspacePresets struct {
	*gentype.ClientWithList[*managementv1.DevsyWorkspacePreset, *managementv1.DevsyWorkspacePresetList]
}

// newDevsyWorkspacePresets returns a DevsyWorkspacePresets
func newDevsyWorkspacePresets(c *ManagementV1Client) *devsyWorkspacePresets {
	return &devsyWorkspacePresets{
		gentype.NewClientWithList[*managementv1.DevsyWorkspacePreset, *managementv1.DevsyWorkspacePresetList](
			"devsyworkspacepresets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementv1.DevsyWorkspacePreset { return &managementv1.DevsyWorkspacePreset{} },
			func() *managementv1.DevsyWorkspacePresetList { return &managementv1.DevsyWorkspacePresetList{} },
		),
	}
}
