// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	managementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	scheme "github.com/devsy-org/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyEnvironmentTemplatesGetter has a method to return a DevsyEnvironmentTemplateInterface.
// A group's client should implement this interface.
type DevsyEnvironmentTemplatesGetter interface {
	DevsyEnvironmentTemplates() DevsyEnvironmentTemplateInterface
}

// DevsyEnvironmentTemplateInterface has methods to work with DevsyEnvironmentTemplate resources.
type DevsyEnvironmentTemplateInterface interface {
	Create(ctx context.Context, devPodEnvironmentTemplate *managementv1.DevsyEnvironmentTemplate, opts metav1.CreateOptions) (*managementv1.DevsyEnvironmentTemplate, error)
	Update(ctx context.Context, devPodEnvironmentTemplate *managementv1.DevsyEnvironmentTemplate, opts metav1.UpdateOptions) (*managementv1.DevsyEnvironmentTemplate, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*managementv1.DevsyEnvironmentTemplate, error)
	List(ctx context.Context, opts metav1.ListOptions) (*managementv1.DevsyEnvironmentTemplateList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *managementv1.DevsyEnvironmentTemplate, err error)
	DevsyEnvironmentTemplateExpansion
}

// devPodEnvironmentTemplates implements DevsyEnvironmentTemplateInterface
type devPodEnvironmentTemplates struct {
	*gentype.ClientWithList[*managementv1.DevsyEnvironmentTemplate, *managementv1.DevsyEnvironmentTemplateList]
}

// newDevsyEnvironmentTemplates returns a DevsyEnvironmentTemplates
func newDevsyEnvironmentTemplates(c *ManagementV1Client) *devPodEnvironmentTemplates {
	return &devPodEnvironmentTemplates{
		gentype.NewClientWithList[*managementv1.DevsyEnvironmentTemplate, *managementv1.DevsyEnvironmentTemplateList](
			"devpodenvironmenttemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementv1.DevsyEnvironmentTemplate { return &managementv1.DevsyEnvironmentTemplate{} },
			func() *managementv1.DevsyEnvironmentTemplateList {
				return &managementv1.DevsyEnvironmentTemplateList{}
			},
		),
	}
}
