// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	storagev1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	scheme "github.com/devsy-org/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyWorkspaceInstancesGetter has a method to return a DevsyWorkspaceInstanceInterface.
// A group's client should implement this interface.
type DevsyWorkspaceInstancesGetter interface {
	DevsyWorkspaceInstances(namespace string) DevsyWorkspaceInstanceInterface
}

// DevsyWorkspaceInstanceInterface has methods to work with DevsyWorkspaceInstance resources.
type DevsyWorkspaceInstanceInterface interface {
	Create(ctx context.Context, devPodWorkspaceInstance *storagev1.DevsyWorkspaceInstance, opts metav1.CreateOptions) (*storagev1.DevsyWorkspaceInstance, error)
	Update(ctx context.Context, devPodWorkspaceInstance *storagev1.DevsyWorkspaceInstance, opts metav1.UpdateOptions) (*storagev1.DevsyWorkspaceInstance, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*storagev1.DevsyWorkspaceInstance, error)
	List(ctx context.Context, opts metav1.ListOptions) (*storagev1.DevsyWorkspaceInstanceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *storagev1.DevsyWorkspaceInstance, err error)
	DevsyWorkspaceInstanceExpansion
}

// devPodWorkspaceInstances implements DevsyWorkspaceInstanceInterface
type devPodWorkspaceInstances struct {
	*gentype.ClientWithList[*storagev1.DevsyWorkspaceInstance, *storagev1.DevsyWorkspaceInstanceList]
}

// newDevsyWorkspaceInstances returns a DevsyWorkspaceInstances
func newDevsyWorkspaceInstances(c *StorageV1Client, namespace string) *devPodWorkspaceInstances {
	return &devPodWorkspaceInstances{
		gentype.NewClientWithList[*storagev1.DevsyWorkspaceInstance, *storagev1.DevsyWorkspaceInstanceList](
			"devpodworkspaceinstances",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *storagev1.DevsyWorkspaceInstance { return &storagev1.DevsyWorkspaceInstance{} },
			func() *storagev1.DevsyWorkspaceInstanceList { return &storagev1.DevsyWorkspaceInstanceList{} },
		),
	}
}
