// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	storagev1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	scheme "github.com/devsy-org/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyWorkspaceTemplatesGetter has a method to return a DevsyWorkspaceTemplateInterface.
// A group's client should implement this interface.
type DevsyWorkspaceTemplatesGetter interface {
	DevsyWorkspaceTemplates() DevsyWorkspaceTemplateInterface
}

// DevsyWorkspaceTemplateInterface has methods to work with DevsyWorkspaceTemplate resources.
type DevsyWorkspaceTemplateInterface interface {
	Create(ctx context.Context, devsyWorkspaceTemplate *storagev1.DevsyWorkspaceTemplate, opts metav1.CreateOptions) (*storagev1.DevsyWorkspaceTemplate, error)
	Update(ctx context.Context, devsyWorkspaceTemplate *storagev1.DevsyWorkspaceTemplate, opts metav1.UpdateOptions) (*storagev1.DevsyWorkspaceTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, devsyWorkspaceTemplate *storagev1.DevsyWorkspaceTemplate, opts metav1.UpdateOptions) (*storagev1.DevsyWorkspaceTemplate, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*storagev1.DevsyWorkspaceTemplate, error)
	List(ctx context.Context, opts metav1.ListOptions) (*storagev1.DevsyWorkspaceTemplateList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *storagev1.DevsyWorkspaceTemplate, err error)
	DevsyWorkspaceTemplateExpansion
}

// devsyWorkspaceTemplates implements DevsyWorkspaceTemplateInterface
type devsyWorkspaceTemplates struct {
	*gentype.ClientWithList[*storagev1.DevsyWorkspaceTemplate, *storagev1.DevsyWorkspaceTemplateList]
}

// newDevsyWorkspaceTemplates returns a DevsyWorkspaceTemplates
func newDevsyWorkspaceTemplates(c *StorageV1Client) *devsyWorkspaceTemplates {
	return &devsyWorkspaceTemplates{
		gentype.NewClientWithList[*storagev1.DevsyWorkspaceTemplate, *storagev1.DevsyWorkspaceTemplateList](
			"devsyworkspacetemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *storagev1.DevsyWorkspaceTemplate { return &storagev1.DevsyWorkspaceTemplate{} },
			func() *storagev1.DevsyWorkspaceTemplateList { return &storagev1.DevsyWorkspaceTemplateList{} },
		),
	}
}
