// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	storagev1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	scheme "github.com/devsy-org/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyEnvironmentTemplatesGetter has a method to return a DevsyEnvironmentTemplateInterface.
// A group's client should implement this interface.
type DevsyEnvironmentTemplatesGetter interface {
	DevsyEnvironmentTemplates() DevsyEnvironmentTemplateInterface
}

// DevsyEnvironmentTemplateInterface has methods to work with DevsyEnvironmentTemplate resources.
type DevsyEnvironmentTemplateInterface interface {
	Create(ctx context.Context, devsyEnvironmentTemplate *storagev1.DevsyEnvironmentTemplate, opts metav1.CreateOptions) (*storagev1.DevsyEnvironmentTemplate, error)
	Update(ctx context.Context, devsyEnvironmentTemplate *storagev1.DevsyEnvironmentTemplate, opts metav1.UpdateOptions) (*storagev1.DevsyEnvironmentTemplate, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*storagev1.DevsyEnvironmentTemplate, error)
	List(ctx context.Context, opts metav1.ListOptions) (*storagev1.DevsyEnvironmentTemplateList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *storagev1.DevsyEnvironmentTemplate, err error)
	DevsyEnvironmentTemplateExpansion
}

// devsyEnvironmentTemplates implements DevsyEnvironmentTemplateInterface
type devsyEnvironmentTemplates struct {
	*gentype.ClientWithList[*storagev1.DevsyEnvironmentTemplate, *storagev1.DevsyEnvironmentTemplateList]
}

// newDevsyEnvironmentTemplates returns a DevsyEnvironmentTemplates
func newDevsyEnvironmentTemplates(c *StorageV1Client) *devsyEnvironmentTemplates {
	return &devsyEnvironmentTemplates{
		gentype.NewClientWithList[*storagev1.DevsyEnvironmentTemplate, *storagev1.DevsyEnvironmentTemplateList](
			"devsyenvironmenttemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *storagev1.DevsyEnvironmentTemplate { return &storagev1.DevsyEnvironmentTemplate{} },
			func() *storagev1.DevsyEnvironmentTemplateList { return &storagev1.DevsyEnvironmentTemplateList{} },
		),
	}
}
