// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	storagev1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	scheme "github.com/devsy-org/api/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevsyWorkspacePresetsGetter has a method to return a DevsyWorkspacePresetInterface.
// A group's client should implement this interface.
type DevsyWorkspacePresetsGetter interface {
	DevsyWorkspacePresets() DevsyWorkspacePresetInterface
}

// DevsyWorkspacePresetInterface has methods to work with DevsyWorkspacePreset resources.
type DevsyWorkspacePresetInterface interface {
	Create(ctx context.Context, devsyWorkspacePreset *storagev1.DevsyWorkspacePreset, opts metav1.CreateOptions) (*storagev1.DevsyWorkspacePreset, error)
	Update(ctx context.Context, devsyWorkspacePreset *storagev1.DevsyWorkspacePreset, opts metav1.UpdateOptions) (*storagev1.DevsyWorkspacePreset, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*storagev1.DevsyWorkspacePreset, error)
	List(ctx context.Context, opts metav1.ListOptions) (*storagev1.DevsyWorkspacePresetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *storagev1.DevsyWorkspacePreset, err error)
	DevsyWorkspacePresetExpansion
}

// devsyWorkspacePresets implements DevsyWorkspacePresetInterface
type devsyWorkspacePresets struct {
	*gentype.ClientWithList[*storagev1.DevsyWorkspacePreset, *storagev1.DevsyWorkspacePresetList]
}

// newDevsyWorkspacePresets returns a DevsyWorkspacePresets
func newDevsyWorkspacePresets(c *StorageV1Client) *devsyWorkspacePresets {
	return &devsyWorkspacePresets{
		gentype.NewClientWithList[*storagev1.DevsyWorkspacePreset, *storagev1.DevsyWorkspacePresetList](
			"devsyworkspacepresets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *storagev1.DevsyWorkspacePreset { return &storagev1.DevsyWorkspacePreset{} },
			func() *storagev1.DevsyWorkspacePresetList { return &storagev1.DevsyWorkspacePresetList{} },
		),
	}
}
