// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	managementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyWorkspaceTemplateLister helps list DevsyWorkspaceTemplates.
// All objects returned here must be treated as read-only.
type DevsyWorkspaceTemplateLister interface {
	// List lists all DevsyWorkspaceTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*managementv1.DevsyWorkspaceTemplate, err error)
	// Get retrieves the DevsyWorkspaceTemplate from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*managementv1.DevsyWorkspaceTemplate, error)
	DevsyWorkspaceTemplateListerExpansion
}

// devPodWorkspaceTemplateLister implements the DevsyWorkspaceTemplateLister interface.
type devPodWorkspaceTemplateLister struct {
	listers.ResourceIndexer[*managementv1.DevsyWorkspaceTemplate]
}

// NewDevsyWorkspaceTemplateLister returns a new DevsyWorkspaceTemplateLister.
func NewDevsyWorkspaceTemplateLister(indexer cache.Indexer) DevsyWorkspaceTemplateLister {
	return &devPodWorkspaceTemplateLister{listers.New[*managementv1.DevsyWorkspaceTemplate](indexer, managementv1.Resource("devpodworkspacetemplate"))}
}
