// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	managementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyWorkspacePresetLister helps list DevsyWorkspacePresets.
// All objects returned here must be treated as read-only.
type DevsyWorkspacePresetLister interface {
	// List lists all DevsyWorkspacePresets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*managementv1.DevsyWorkspacePreset, err error)
	// Get retrieves the DevsyWorkspacePreset from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*managementv1.DevsyWorkspacePreset, error)
	DevsyWorkspacePresetListerExpansion
}

// devsyWorkspacePresetLister implements the DevsyWorkspacePresetLister interface.
type devsyWorkspacePresetLister struct {
	listers.ResourceIndexer[*managementv1.DevsyWorkspacePreset]
}

// NewDevsyWorkspacePresetLister returns a new DevsyWorkspacePresetLister.
func NewDevsyWorkspacePresetLister(indexer cache.Indexer) DevsyWorkspacePresetLister {
	return &devsyWorkspacePresetLister{listers.New[*managementv1.DevsyWorkspacePreset](indexer, managementv1.Resource("devsyworkspacepreset"))}
}
