// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	managementv1 "github.com/devsy-org/api/pkg/apis/management/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DevsyWorkspaceInstanceLister helps list DevsyWorkspaceInstances.
// All objects returned here must be treated as read-only.
type DevsyWorkspaceInstanceLister interface {
	// List lists all DevsyWorkspaceInstances in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*managementv1.DevsyWorkspaceInstance, err error)
	// DevsyWorkspaceInstances returns an object that can list and get DevsyWorkspaceInstances.
	DevsyWorkspaceInstances(namespace string) DevsyWorkspaceInstanceNamespaceLister
	DevsyWorkspaceInstanceListerExpansion
}

// devPodWorkspaceInstanceLister implements the DevsyWorkspaceInstanceLister interface.
type devPodWorkspaceInstanceLister struct {
	listers.ResourceIndexer[*managementv1.DevsyWorkspaceInstance]
}

// NewDevsyWorkspaceInstanceLister returns a new DevsyWorkspaceInstanceLister.
func NewDevsyWorkspaceInstanceLister(indexer cache.Indexer) DevsyWorkspaceInstanceLister {
	return &devPodWorkspaceInstanceLister{listers.New[*managementv1.DevsyWorkspaceInstance](indexer, managementv1.Resource("devpodworkspaceinstance"))}
}

// DevsyWorkspaceInstances returns an object that can list and get DevsyWorkspaceInstances.
func (s *devPodWorkspaceInstanceLister) DevsyWorkspaceInstances(namespace string) DevsyWorkspaceInstanceNamespaceLister {
	return devPodWorkspaceInstanceNamespaceLister{listers.NewNamespaced[*managementv1.DevsyWorkspaceInstance](s.ResourceIndexer, namespace)}
}

// DevsyWorkspaceInstanceNamespaceLister helps list and get DevsyWorkspaceInstances.
// All objects returned here must be treated as read-only.
type DevsyWorkspaceInstanceNamespaceLister interface {
	// List lists all DevsyWorkspaceInstances in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*managementv1.DevsyWorkspaceInstance, err error)
	// Get retrieves the DevsyWorkspaceInstance from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*managementv1.DevsyWorkspaceInstance, error)
	DevsyWorkspaceInstanceNamespaceListerExpansion
}

// devPodWorkspaceInstanceNamespaceLister implements the DevsyWorkspaceInstanceNamespaceLister
// interface.
type devPodWorkspaceInstanceNamespaceLister struct {
	listers.ResourceIndexer[*managementv1.DevsyWorkspaceInstance]
}
