// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/devsy-org/api/pkg/apis/management/v1"
	managementv1 "github.com/devsy-org/api/pkg/clientset/versioned/typed/management/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDevsyEnvironmentTemplates implements DevsyEnvironmentTemplateInterface
type fakeDevsyEnvironmentTemplates struct {
	*gentype.FakeClientWithList[*v1.DevsyEnvironmentTemplate, *v1.DevsyEnvironmentTemplateList]
	Fake *FakeManagementV1
}

func newFakeDevsyEnvironmentTemplates(fake *FakeManagementV1) managementv1.DevsyEnvironmentTemplateInterface {
	return &fakeDevsyEnvironmentTemplates{
		gentype.NewFakeClientWithList[*v1.DevsyEnvironmentTemplate, *v1.DevsyEnvironmentTemplateList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("devpodenvironmenttemplates"),
			v1.SchemeGroupVersion.WithKind("DevsyEnvironmentTemplate"),
			func() *v1.DevsyEnvironmentTemplate { return &v1.DevsyEnvironmentTemplate{} },
			func() *v1.DevsyEnvironmentTemplateList { return &v1.DevsyEnvironmentTemplateList{} },
			func(dst, src *v1.DevsyEnvironmentTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DevsyEnvironmentTemplateList) []*v1.DevsyEnvironmentTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.DevsyEnvironmentTemplateList, items []*v1.DevsyEnvironmentTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
