// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	v1 "github.com/devsy-org/api/pkg/apis/management/v1"
	managementv1 "github.com/devsy-org/api/pkg/clientset/versioned/typed/management/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	testing "k8s.io/client-go/testing"
)

// fakeDevsyWorkspaceInstances implements DevsyWorkspaceInstanceInterface
type fakeDevsyWorkspaceInstances struct {
	*gentype.FakeClientWithList[*v1.DevsyWorkspaceInstance, *v1.DevsyWorkspaceInstanceList]
	Fake *FakeManagementV1
}

func newFakeDevsyWorkspaceInstances(fake *FakeManagementV1, namespace string) managementv1.DevsyWorkspaceInstanceInterface {
	return &fakeDevsyWorkspaceInstances{
		gentype.NewFakeClientWithList[*v1.DevsyWorkspaceInstance, *v1.DevsyWorkspaceInstanceList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("devpodworkspaceinstances"),
			v1.SchemeGroupVersion.WithKind("DevsyWorkspaceInstance"),
			func() *v1.DevsyWorkspaceInstance { return &v1.DevsyWorkspaceInstance{} },
			func() *v1.DevsyWorkspaceInstanceList { return &v1.DevsyWorkspaceInstanceList{} },
			func(dst, src *v1.DevsyWorkspaceInstanceList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DevsyWorkspaceInstanceList) []*v1.DevsyWorkspaceInstance {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.DevsyWorkspaceInstanceList, items []*v1.DevsyWorkspaceInstance) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}

// Up takes the representation of a devPodWorkspaceInstanceUp and creates it.  Returns the server's representation of the devPodWorkspaceInstanceUp, and an error, if there is any.
func (c *fakeDevsyWorkspaceInstances) Up(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceUp *v1.DevsyWorkspaceInstanceUp, opts metav1.CreateOptions) (result *v1.DevsyWorkspaceInstanceUp, err error) {
	emptyResult := &v1.DevsyWorkspaceInstanceUp{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateSubresourceActionWithOptions(c.Resource(), devPodWorkspaceInstanceName, "up", c.Namespace(), devPodWorkspaceInstanceUp, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DevsyWorkspaceInstanceUp), err
}

// Stop takes the representation of a devPodWorkspaceInstanceStop and creates it.  Returns the server's representation of the devPodWorkspaceInstanceStop, and an error, if there is any.
func (c *fakeDevsyWorkspaceInstances) Stop(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceStop *v1.DevsyWorkspaceInstanceStop, opts metav1.CreateOptions) (result *v1.DevsyWorkspaceInstanceStop, err error) {
	emptyResult := &v1.DevsyWorkspaceInstanceStop{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateSubresourceActionWithOptions(c.Resource(), devPodWorkspaceInstanceName, "stop", c.Namespace(), devPodWorkspaceInstanceStop, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DevsyWorkspaceInstanceStop), err
}

// Troubleshoot takes name of the devPodWorkspaceInstance, and returns the corresponding devPodWorkspaceInstanceTroubleshoot object, and an error if there is any.
func (c *fakeDevsyWorkspaceInstances) Troubleshoot(ctx context.Context, devPodWorkspaceInstanceName string, options metav1.GetOptions) (result *v1.DevsyWorkspaceInstanceTroubleshoot, err error) {
	emptyResult := &v1.DevsyWorkspaceInstanceTroubleshoot{}
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceActionWithOptions(c.Resource(), c.Namespace(), "troubleshoot", devPodWorkspaceInstanceName, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DevsyWorkspaceInstanceTroubleshoot), err
}

// Cancel takes the representation of a devPodWorkspaceInstanceCancel and creates it.  Returns the server's representation of the devPodWorkspaceInstanceCancel, and an error, if there is any.
func (c *fakeDevsyWorkspaceInstances) Cancel(ctx context.Context, devPodWorkspaceInstanceName string, devPodWorkspaceInstanceCancel *v1.DevsyWorkspaceInstanceCancel, opts metav1.CreateOptions) (result *v1.DevsyWorkspaceInstanceCancel, err error) {
	emptyResult := &v1.DevsyWorkspaceInstanceCancel{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateSubresourceActionWithOptions(c.Resource(), devPodWorkspaceInstanceName, "cancel", c.Namespace(), devPodWorkspaceInstanceCancel, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.DevsyWorkspaceInstanceCancel), err
}
