// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/devsy-org/api/pkg/apis/management/v1"
	managementv1 "github.com/devsy-org/api/pkg/clientset/versioned/typed/management/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDevsyWorkspacePresets implements DevsyWorkspacePresetInterface
type fakeDevsyWorkspacePresets struct {
	*gentype.FakeClientWithList[*v1.DevsyWorkspacePreset, *v1.DevsyWorkspacePresetList]
	Fake *FakeManagementV1
}

func newFakeDevsyWorkspacePresets(fake *FakeManagementV1) managementv1.DevsyWorkspacePresetInterface {
	return &fakeDevsyWorkspacePresets{
		gentype.NewFakeClientWithList[*v1.DevsyWorkspacePreset, *v1.DevsyWorkspacePresetList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("devpodworkspacepresets"),
			v1.SchemeGroupVersion.WithKind("DevsyWorkspacePreset"),
			func() *v1.DevsyWorkspacePreset { return &v1.DevsyWorkspacePreset{} },
			func() *v1.DevsyWorkspacePresetList { return &v1.DevsyWorkspacePresetList{} },
			func(dst, src *v1.DevsyWorkspacePresetList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DevsyWorkspacePresetList) []*v1.DevsyWorkspacePreset {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.DevsyWorkspacePresetList, items []*v1.DevsyWorkspacePreset) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
