// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	storagev1 "github.com/devsy-org/api/pkg/clientset/versioned/typed/storage/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDevsyWorkspaceInstances implements DevsyWorkspaceInstanceInterface
type fakeDevsyWorkspaceInstances struct {
	*gentype.FakeClientWithList[*v1.DevsyWorkspaceInstance, *v1.DevsyWorkspaceInstanceList]
	Fake *FakeStorageV1
}

func newFakeDevsyWorkspaceInstances(fake *FakeStorageV1, namespace string) storagev1.DevsyWorkspaceInstanceInterface {
	return &fakeDevsyWorkspaceInstances{
		gentype.NewFakeClientWithList[*v1.DevsyWorkspaceInstance, *v1.DevsyWorkspaceInstanceList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("devpodworkspaceinstances"),
			v1.SchemeGroupVersion.WithKind("DevsyWorkspaceInstance"),
			func() *v1.DevsyWorkspaceInstance { return &v1.DevsyWorkspaceInstance{} },
			func() *v1.DevsyWorkspaceInstanceList { return &v1.DevsyWorkspaceInstanceList{} },
			func(dst, src *v1.DevsyWorkspaceInstanceList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DevsyWorkspaceInstanceList) []*v1.DevsyWorkspaceInstance {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.DevsyWorkspaceInstanceList, items []*v1.DevsyWorkspaceInstance) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
