// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/devsy-org/api/pkg/apis/storage/v1"
	storagev1 "github.com/devsy-org/api/pkg/clientset/versioned/typed/storage/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDevsyWorkspaceTemplates implements DevsyWorkspaceTemplateInterface
type fakeDevsyWorkspaceTemplates struct {
	*gentype.FakeClientWithList[*v1.DevsyWorkspaceTemplate, *v1.DevsyWorkspaceTemplateList]
	Fake *FakeStorageV1
}

func newFakeDevsyWorkspaceTemplates(fake *FakeStorageV1) storagev1.DevsyWorkspaceTemplateInterface {
	return &fakeDevsyWorkspaceTemplates{
		gentype.NewFakeClientWithList[*v1.DevsyWorkspaceTemplate, *v1.DevsyWorkspaceTemplateList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("devpodworkspacetemplates"),
			v1.SchemeGroupVersion.WithKind("DevsyWorkspaceTemplate"),
			func() *v1.DevsyWorkspaceTemplate { return &v1.DevsyWorkspaceTemplate{} },
			func() *v1.DevsyWorkspaceTemplateList { return &v1.DevsyWorkspaceTemplateList{} },
			func(dst, src *v1.DevsyWorkspaceTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1.DevsyWorkspaceTemplateList) []*v1.DevsyWorkspaceTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.DevsyWorkspaceTemplateList, items []*v1.DevsyWorkspaceTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
